name: Python Test
on: [push, pull_request] # pushされた時とPRした時に実行

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 # リポジトリのコードを取得

    - name: Set up python env
      uses: actions/setup-python@v5
      whih:
        python-version: '3.10'
    
    - name: Install
      run: 
        python -m pip install --upgrade pip
        pip install pytest
        if [-f requirements.txt]; then pip install -r requirements.txt

    - name: ADD PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}/src" >> $GITHUB_ENV 

    - name: Run Test
      run: |
        pytest
      continue-on-error: true